### ISSUE TITLE
Chef not following the spec

### ISSUE THREAD

**Issue by Seggan** [nilaymaj/esolang-park#6]
In the Chef notes, you note that you cannot determine a correct verb plural. However, in the [spec](https://www.dangermouse.net/esoteric/chef.html), it states that the correct plural is always the verb followed by `ed`. For example: `X` -> `xed`, `Grow` -> `growed`.

**Comment by nilaymaj** [comment]
Hi @Seggan, and thanks a lot for submitting this and the PR! I'm assuming you're talking about the following section in the spec:

> _Verb [the ingredient] until verbed._
This marks the end of a loop. It must appear as a matched pair with the above statement. verbed must match the Verb in the matching loop start statement. The Verb in this statement may be arbitrary and is ignored. If the ingredient appears in this statement, its value is decremented by 1 when this statement executes. The ingredient does not have to match the ingredient in the matching loop start statement.

While it does use "verbed" in the text, I don't think it implies that the corresponding past form is going to be `"verb"+ed`. For instance, check the [Fibonacci Numbers with Caramel Sauce](https://www.dangermouse.net/esoteric/chef_fib.html) example program linked in the spec: for the loop in "Caramel Sauce" auxiliary recipe, the verb pair is "Caramelise" and "caramelised". In my understanding, the spec doesn't strictly specify if the verb pair should be grammatically valid or just `"verb"+(e)d`.

Adding `ed` as you did in the PR may be a fantastic middle-grounds though. In fact, I think we can cover a whole lot of cases with the following heuristic:
- If "verb" ends with "e", closing term is `"verb"+d`
- Else, closing term is `"verb"+ed`

This will be much better than the current situation where _all_ Chef loops have to be modified for Esolang Park. I guess we should also take a look at the interpreter used in [TIO](https://tio.run/#chef) and how it tackles this problem.

Let me know what you think, or if I'm missing something in the spec.

**Comment by Seggan** [comment]
TIO just [appends](https://github.com/mpw96/perl-Acme-Chef/blob/12f32a8d41ef14bcd5be0b8a30ed8c1cecf77a35/lib/Acme/Chef/Recipe.pm#L247) `ed` to every verb

**Comment by Seggan** [comment]
I don't really know how to implement this in regex while strictly keeping to your scheme, `(\1)e?d` comes to mind but it'd allow things like `Verb until verbd`

**Comment by nilaymaj** [comment]
I think the verb matching can be done in the parser code instead of inside the regex:

https://github.com/nilaymaj/esolang-park/blob/78996f849d60aae81060e36ebbb8ad2f6ea01217/languages/chef/parser/index.ts#L194-L200

This will also allow better parsing error messages to the user. A line not satisfying the regex would mean a cryptic "Unknown instruction", while here we can properly communicate what `verb`/`verbed` is expected for closing the loop.

There's a stub function `toPresentTense` currently used in the parser:

https://github.com/nilaymaj/esolang-park/blob/78996f849d60aae81060e36ebbb8ad2f6ea01217/languages/chef/parser/core.ts#L13-L24 

Flipping this to `toPastTense` with the above `d/ed` logic and using this in the parser validation should work fine I think. The regex can then be left unmodified so that it catches the broad instruction format properly.

**Comment by nilaymaj** [comment]
Closing this as the related PR is merged now. Thanks a lot!
