### ISSUE TITLE
Allow for speed less than 5 ms

### ISSUE THREAD

**Issue by Seggan** [nilaymaj/esolang-park#9]
Sometimes you just want your code to run as fast as possible. Even at 5 ms computing the Taylor series for atan to 64 terms (don't ask) takes around 2 minutes.

**Comment by nilaymaj** [comment]
Yep, Esolang Park is a pretty slow experience if you just want to run some code without any frills. The execution interval is currently limited to at or above 5ms because the React render takes quite a lot of time as compared to the execution time. This is also mentioned in the [wiki](https://github.com/nilaymaj/esolang-park/wiki/Architecture#performance) in a bit more detail. 

A possibly better solution than the one mentioned in the wiki is to rework how messages from the message queue are processed. If we perform batch processing of messages say every 50 ms (or atleast debounce the visualization rerender), it will allow us a very comfortable window to re-render almost anything we want. This is off the top of my head though - there may be some blockers here regarding how the editor highlights and code output are updated on message processing. But I think this should be feasible.

Let me see if I can take a look at this on the weekend.

**Comment by nilaymaj** [comment]
Okay, this is trickier than I thought. Removing the sleep() call on the execution controller side will cause the while-loop to block processing of messages from the main thread - meaning pause and stop actions won't work. And keeping a sleep(0) adds too much event-loop overhead - it's not much faster than 5ms.

**Comment by nilaymaj** [comment]
The execution interval input now allows 0ms as input. @Seggan How long does your program take to execute on this setting?

**Comment by Seggan** [comment]
> The execution interval input now allows 0ms as input. @Seggan How long does your program take to execute on this setting?

Around a second for 64 iterations now! Thank you so much! It's so much less painful now!

**Comment by Seggan** [comment]
Apologies for necroposting, but [this](https://codegolf.stackexchange.com/a/276793/107299) is the culmination of my efforts, with your help. Thought you might wanna see it.

**Comment by nilaymaj** [comment]
That... is awesome! Tried the program as well - the heap and anti-heap technique feels super satisfying. My favorite codegolf answers are always those that invent a whole new dev stack, it's just mindblowing to witness the effort itself even if it strays a bit from the "golf" part. The rabbit hole of [implementing Tetris in CGoL](https://codegolf.stackexchange.com/a/142673), for example.

You're a legend, and I'm glad to have played a little part in that 8 month journey. You've made my week! :D

(ran the program on 5ms interval, and it's still running and running and ... I can understand that pain very well now)
